"""add meters and readings

Revision ID: 9c9aa3ad280e
Revises: c8ed1cfbf9fd
Create Date: 2026-09-28 18:40:05.212588

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9c9aa3ad280e'
down_revision: str | None = 'c8ed1cfbf9fd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_service_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('initial_value', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('installed_at', sa.Date(), nullable=True),
    sa.Column('replaced_at', sa.Date(), nullable=True),
    sa.Column('replaced_by_meter_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_service_id'], ['property_services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replaced_by_meter_id'], ['meters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meters_property_service_id'), 'meters', ['property_service_id'], unique=False)
    op.create_index(op.f('ix_meters_replaced_at'), 'meters', ['replaced_at'], unique=False)
    op.create_table('readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('taken_at', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meter_id', 'taken_at', name='uq_meter_reading_date')
    )
    op.create_index(op.f('ix_readings_meter_id'), 'readings', ['meter_id'], unique=False)
    op.create_index(op.f('ix_readings_taken_at'), 'readings', ['taken_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_readings_taken_at'), table_name='readings')
    op.drop_index(op.f('ix_readings_meter_id'), table_name='readings')
    op.drop_table('readings')
    op.drop_index(op.f('ix_meters_replaced_at'), table_name='meters')
    op.drop_index(op.f('ix_meters_property_service_id'), table_name='meters')
    op.drop_table('meters')
    # ### end Alembic commands ###