"""add properties

Revision ID: c8ed1cfbf9fd
Revises: a86b5e9a4b42
Create Date: 2026-09-28 18:16:37.541714

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c8ed1cfbf9fd'
down_revision: str | None = 'a86b5e9a4b42'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_household_id'), 'properties', ['household_id'], unique=False)
    op.create_index(op.f('ix_properties_is_archived'), 'properties', ['is_archived'], unique=False)
    op.create_index(op.f('ix_properties_type'), 'properties', ['type'], unique=False)
    op.create_table('property_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('closed_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'service_type_id', name='uq_prop_service')
    )
    op.create_index(op.f('ix_property_services_is_active'), 'property_services', ['is_active'], unique=False)
    op.create_index(op.f('ix_property_services_property_id'), 'property_services', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_services_service_type_id'), 'property_services', ['service_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_services_service_type_id'), table_name='property_services')
    op.drop_index(op.f('ix_property_services_property_id'), table_name='property_services')
    op.drop_index(op.f('ix_property_services_is_active'), table_name='property_services')
    op.drop_table('property_services')
    op.drop_index(op.f('ix_properties_type'), table_name='properties')
    op.drop_index(op.f('ix_properties_is_archived'), table_name='properties')
    op.drop_index(op.f('ix_properties_household_id'), table_name='properties')
    op.drop_table('properties')
    # ### end Alembic commands ###