"""add reminders and notifications

Revision ID: d9c69099c927
Revises: 958060ac9c04
Create Date: 2026-09-28 19:04:56.155346

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd9c69099c927'
down_revision: str | None = '958060ac9c04'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fcm_token', sa.String(length=512), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('device_name', sa.String(length=200), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fcm_token')
    )
    op.create_index(op.f('ix_devices_is_active'), 'devices', ['is_active'], unique=False)
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel', name='uq_user_channel')
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    op.create_table('reminder_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('charge_id', sa.Integer(), nullable=True),
    sa.Column('service_type_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('days_before', sa.Integer(), nullable=False),
    sa.Column('channels', sa.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('days_before >= 0', name='ck_days_before_non_negative'),
    sa.ForeignKeyConstraint(['charge_id'], ['charges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_rules_charge_id'), 'reminder_rules', ['charge_id'], unique=False)
    op.create_index(op.f('ix_reminder_rules_household_id'), 'reminder_rules', ['household_id'], unique=False)
    op.create_index(op.f('ix_reminder_rules_is_active'), 'reminder_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_reminder_rules_service_type_id'), 'reminder_rules', ['service_type_id'], unique=False)
    op.create_index(op.f('ix_reminder_rules_user_id'), 'reminder_rules', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('charge_id', sa.Integer(), nullable=True),
    sa.Column('reminder_rule_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempts >= 0', name='ck_attempts_non_negative'),
    sa.ForeignKeyConstraint(['charge_id'], ['charges.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reminder_rule_id'], ['reminder_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'charge_id', 'reminder_rule_id', 'channel', 'scheduled_date', name='uq_notification_dedup')
    )
    op.create_index(op.f('ix_notifications_charge_id'), 'notifications', ['charge_id'], unique=False)
    op.create_index(op.f('ix_notifications_reminder_rule_id'), 'notifications', ['reminder_rule_id'], unique=False)
    op.create_index(op.f('ix_notifications_scheduled_at'), 'notifications', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_notifications_scheduled_date'), 'notifications', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_scheduled_date'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_scheduled_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_reminder_rule_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_charge_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_reminder_rules_user_id'), table_name='reminder_rules')
    op.drop_index(op.f('ix_reminder_rules_service_type_id'), table_name='reminder_rules')
    op.drop_index(op.f('ix_reminder_rules_is_active'), table_name='reminder_rules')
    op.drop_index(op.f('ix_reminder_rules_household_id'), table_name='reminder_rules')
    op.drop_index(op.f('ix_reminder_rules_charge_id'), table_name='reminder_rules')
    op.drop_table('reminder_rules')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_is_active'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###